# Generated by Django 5.2.5 on 2025-08-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, default='group_images/default.png', null=True, upload_to='group_images/'),
        ),
    ]
